### ISSUE TITLE
update version to 2.10.2?

### ISSUE THREAD

**Issue by chaomao** [derekprior/momentjs-rails#31]

**Comment by derekprior** [comment]
I don't' really maintain this any more, but I'm happy to merge a well-done PR when I get a chance. @brtdv also has commit and the rights to update the gem.

**Comment by chaomao** [comment]
sure~
I will update it and make a pr

2015-04-10 11:25 GMT+08:00 Derek Prior <notifications@github.com>:

> I don't' really maintain this any more, but I'm happy to merge a well-done
> PR when I get a chance. @brtdv <https://github.com/brtdv> also has commit
> and the rights to update the gem.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/derekprior/momentjs-rails/issues/31#issuecomment-91417141>
> .
>



-- 
I'm looking forward you~

**Comment by dbackowski** [comment]
I made a PR for that.

**Comment by chaomao** [comment]
fantastic

2015-04-23 17:30 GMT+08:00 Damian Baćkowski <notifications@github.com>:

> I made a PR for that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/derekprior/momentjs-rails/issues/31#issuecomment-95510295>
> .
>



-- 
I'm looking forward you~

**Comment by derekprior** [comment]
All set. 2.10.2 is out.
