### ISSUE TITLE
Consider including moment-timezone.js

### ISSUE THREAD

**Issue by dallas** [derekprior/momentjs-rails#36]
moment.js deprecated the use of the timezone abbreviations (e.g. "PST") in version 1.6.0. The moment-timezone.js library, however, adds support for those abbreviations back in so that the "z" and "zz" formatters can be used to properly display them. Please consider adding that library to this project so that people who want to take advantage of that library can simply `#= require moment-timezone`.

Thank you.

**Comment by derekprior** [comment]
We've had similar issues before (#19, #6) and my feelings are unchanged. These plugins are separate libraries. If you want to use rails asset gems for these, I'd consider creating `momentjs_timezone-rails`, which could depend on this gem.

What I'd actually do I use rails-assets.org and get a gem that automatically pulls from bower. I think these asset gems are ultimately a less desirable solution than that.
