### ISSUE TITLE
export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by johan-smits** [derekprior/momentjs-rails#61]
With version `2.29.1` the javascript fails to work with a normal asset pipeline. Caused by #60

`export declarations may only appear at top level of a module`.

I guess just the export needs to be removed?

**Comment by HADDADSOHAIB** [comment]
I just spent a whole day trying to solve this, no luck. a quick work around is to go back to v 2.20.1

**Comment by derekprior** [comment]
Fixed with 2.29.1.1. Thanks @ashkulz 

https://rubygems.org/gems/momentjs-rails/versions/2.29.1.1
